ersion: apps/v1
kind: Deployment
metadata:
  name: underwater-app-github
  labels:
    app: test-node-app
spec:
  selector:
    matchLabels:
        app: test-node-app
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: test-node-app
    spec:
      containers:
        - name: test-node-app
          image: 750552667626.dkr.ecr.us-east-2.amazonaws.com/test-node-app:latest
          ports:
            - containerPort: 8000
              protocol: TCP
          imagePullPolicy: Always